# Web UI 自动化测试配置文件

# 浏览器配置
browser:
  # 浏览器类型: chromium, firefox, webkit
  type: "chromium"
  # 是否无头模式
  headless: true
  # 视口大小
  viewport:
    width: 1920
    height: 1080
  # 是否禁用视口 (全屏模式),必须在args中添加"--start-maximized"才能生效
  no_viewport: true
  # 用户代理 (可选)
  user_agent: null
  # 语言环境
  locale: "zh-CN"
  # 时区
  timezone: "Asia/Shanghai"
  # 额外的HTTP头 (可选)
  extra_http_headers: null
  # 是否忽略HTTPS错误
  ignore_https_errors: true
  # 操作延迟时间(毫秒)
  slow_mo: 0
  # 浏览器启动参数
  args: ["--start-maximized"]

# 超时配置 (单位: 毫秒)
timeouts:
  # 默认超时时间
  default: 10000
  # 短超时时间
  short: 3000
  # 长超时时间
  long: 30000
  # 导航超时时间
  navigation: 30000

# 日志配置
logging:
  # 总体日志级别
  level: "INFO"
  # 日志目录
  directory: "logs"
  # 控制台输出
  console:
    enabled: true
    level: "INFO"
  # 轮转策略
  rotation:
    # size 或 time
    type: "size"
    # size 策略：最大文件大小（字节）
    max_bytes: 5000000
    # time 策略：分割周期，如 S/M/H/D/W0-W6
    when: "D"
    # time 策略：间隔（配合 when 使用）
    interval: 1
    # 历史文件保留数量（同时用于自动清理）
    backup_count: 7
    # 文件编码
    encoding: "utf-8"
  # 统一格式
  format:
    fmt: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  # 每个级别单独文件（true 时分别写入 debug/info/warning/error.log）
  per_level_files: true

# 截图配置
screenshots:
  # 是否启用失败自动截图
  enabled: true
  # 截图保存目录（相对于项目根）
  directory: "reports/screenshots"
  # 是否整页截图
  full_page: true
  # 图片类型：png 或 jpeg
  type: "png"
  # 可选：需要遮挡的选择器列表（避免泄露敏感信息）
  mask_selectors: []

# 视频录制配置
videos:
  # 录制模式：all（全部）、failed_only（仅失败）、disabled（关闭）
  mode: "failed_only"
  # 视频保存目录（相对于项目根）
  directory: "reports/videos"
  # 可选：录像分辨率，降低清晰度可减少体积
  size:
    width: 1280
    height: 720

# Allure 配置（报告与标签、附件策略）
allure:
  # 结果与报告目录
  results_dir: "reports/allure-results"
  report_dir: "reports/allure-report"

  # 标签策略（保持顶级子包为 parentSuite 与 package）
  labels:
    derive_parent_suite: "top_level_subpackage"
    package_strategy: "top_level"
    enable_subsuite: false

  # 附件策略
  attachments:
    screenshot_on_failure: true
    video_on_failure: true

  # 环境附加信息（将合并到 environment.properties）
  environment:
    extra: {}

  # 自定义分类规则文件（可选），如存在则覆盖默认分类
  categories_file: null

  # 执行器信息（可选），显示在报告信息面板
  executor: null